### ISSUE TITLE
Error in the retodfa.png table.

### ISSUE THREAD

**Issue by Abhishek477** [ckshitij/RE_TO_DFA#1]
Hello,

The table entry for ROW = "**A cat node n = C1C2**" under column name = "**lastpos (n)**" , the else condition should be "**lastpos (C2)**" instead of "**lastpos (C1)**".

Can I conclude that the code doesn't have this error?
If the code is constructed on the basis of the above-mentioned error, please inform me the necessary changes to be made. I want this code for my project.

Thank you!

_Kumar Abhishek_
Indian Institute of Engineering Science and Technology, Shibpur.
Dept. of IT

@ckshitij

**Comment by ckshitij** [comment]
The code is working properly. Actually, I wrote this code for my practical exam it worked for all the test cases and the image is not related to code this is only for the tutorial and the link is also shared in Readme.md. I uploaded this code for my batchmate and my juniors, I hope it will work for you.

If you need any kind of help you can raise an issue.
